# Generated by Django 5.1.7 on 2025-06-29 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "ref",
                    models.IntegerField(
                        help_text="This field is mapped with PokeAPI's pokemon Id.",
                        unique=True,
                    ),
                ),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(blank=True, null=True)),
                ("avatar", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "pokemons",
            },
        ),
        migrations.CreateModel(
            name="PokemonAbility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("is_hidden", models.BooleanField(default=False)),
                ("slot", models.IntegerField(blank=True, null=True)),
                (
                    "pokemon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abilities",
                        to="pokemon.pokemon",
                    ),
                ),
            ],
            options={
                "db_table": "pokemon_abilities",
            },
        ),
        migrations.CreateModel(
            name="PokemonMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "pokemon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="pokemon.pokemon",
                    ),
                ),
            ],
            options={
                "db_table": "pokemon_moves",
            },
        ),
        migrations.CreateModel(
            name="PokemonStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("base_stat", models.IntegerField(blank=True, null=True)),
                ("effort", models.IntegerField(blank=True, null=True)),
                (
                    "pokemon_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="pokemon.pokemon",
                    ),
                ),
            ],
            options={
                "db_table": "pokemon_stats",
            },
        ),
    ]
